Repository georchestra/georchestra, pull requests merged in 2018-04, with the labels that each got.

#2000 mapfishapp - allow reading KML 3D
  mapfishapp/src/main/webapp/app/js/GEOR_fileupload.js
Labels: 15.12, bug

#2016 Ldapadmin - Restore css rule on 'create_org_div'
  ldapadmin/src/main/webapp/account/css/ldapadmin.css
Labels: 16.12

#2015 GS - fixing dependencies inclusions
  geoserver/webapp/pom.xml
Labels: 17.12
