Repository georchestra/georchestra, pull requests merged in 2018-09, with the labels that each got.

#2166 proxy - add documentation regarding app integration
  security-proxy/README.md
Labels: 18.06

#2169 http-forwarded jetty module added
  analytics/src/docker/Dockerfile
  atlas/src/docker/Dockerfile
  cas-server-webapp/src/docker/Dockerfile
  console/src/docker/Dockerfile
  extractorapp/src/docker/Dockerfile
  geoserver/webapp/src/docker/Dockerfile
  geowebcache-webapp/src/docker/Dockerfile
  header/src/docker/Dockerfile
  mapfishapp/src/docker/Dockerfile
  security-proxy/src/docker/Dockerfile
Labels: bug

#2175 Unhardcode /mapfishapp/ to enforce SLD 1.0.0 when the style comes fro…
  mapfishapp/src/main/webapp/app/js/GEOR_ows.js
Labels: enhancement
