Repository georchestra/georchestra, pull requests merged in 2018-11, with the labels that each got.

#2232 extractor addon - do not modify map extent when extracting
  mapfishapp/src/main/webapp/app/addons/extractor/js/main.js
Labels: 18.06, enhancement

#2159 Add support for import/export org's area as CSV
  console/src/main/webapp/manager/app/assets/lang/de.json
  console/src/main/webapp/manager/app/assets/lang/en.json
  console/src/main/webapp/manager/app/assets/lang/es.json
  console/src/main/webapp/manager/app/assets/lang/fr.json
  console/src/main/webapp/manager/app/components/area/area.es6
  console/src/main/webapp/manager/app/components/area/area.tpl.html
  console/src/main/webapp/manager/app/styles/app.less
Labels: feature

#2263 Common - add log details on database parameters when waiting for connection
  commons/src/main/java/org/georchestra/commons/WaitForDb.java
Labels: enhancement
