Repository georchestra/georchestra, pull requests merged in 2019-02, with the labels that each got.

#2425 Remove useless code in console
  console/src/main/resources/META-INF/spring/applicationContext.xml
Labels: enhancement

#2502 mapfishapp - fix vector layer query error
  mapfishapp/src/main/webapp/app/js/GEOR_ResultsPanel.js
Labels: 16.12

#2513 LDAP - fix pendingorg dn
  ldap/georchestra.ldif
Labels: bug

#2490 use commons-httpclient from atlassian fork to fix #2183
  mapfishapp/pom.xml
  pom.xml
Labels: enhancement
