Repository georchestra/georchestra, pull requests merged in 2019-07, with the labels that each got.

#2656 Fix regression with ldap scheme
  cas-server-webapp/src/main/webapp/WEB-INF/deployerConfigContext.xml
  console/src/it/resources/webmvc-config-test.xml
  console/src/main/webapp/WEB-INF/spring/webmvc-config.xml
  security-proxy/src/main/webapp/WEB-INF/applicationContext-security.xml
Labels: enhancement

#2658 run maven with --no-transfer-progress on travis-ci
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  .travis.yml
  mvnw
  mvnw.cmd
Labels: bug

#2652 [console] Allow multiselection of users
  console/src/main/webapp/manager/app/assets/lang/de.json
  console/src/main/webapp/manager/app/assets/lang/en.json
  console/src/main/webapp/manager/app/assets/lang/es.json
  console/src/main/webapp/manager/app/assets/lang/fr.json
  console/src/main/webapp/manager/app/components/users/users.es6
  console/src/main/webapp/manager/app/components/users/users.tpl.html
  console/src/main/webapp/manager/app/styles/app.less
  console/src/main/webapp/manager/brunch-config.coffee
  console/src/main/webapp/manager/vendor/bootstrap.min.js
Labels: feature
