Repository georchestra/georchestra, pull requests merged in 2020-01, with the labels that each got.

#2869 console - fix area persisting logic
  console/src/main/java/org/georchestra/console/ds/OrgsDao.java
  console/src/main/java/org/georchestra/console/ws/backoffice/orgs/OrgsController.java
Labels: bug

#2872 console - (re ?)introducing urlrewrite (#2449)
  console/src/main/webapp/WEB-INF/urlrewrite.xml
  console/src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#2874 console - adding orgType as mandatory fields (#2666)
  console/src/main/java/org/georchestra/console/ws/utils/Validation.java
  console/src/test/java/org/georchestra/console/ws/utils/ValidationTest.java
Labels: bug

#2870 console - it should be possible to make orgs extra fields mandatory
  analytics/src/test/java/org/georchestra/analytics/StatisticsControllerIT.java
  console/src/main/java/org/georchestra/console/ws/editorgdetails/EditOrgDetailsFormController.java
  console/src/main/java/org/georchestra/console/ws/newaccount/NewAccountFormController.java
Labels: bug

#2777 console - log relevant information in home, user and logs page
  console/pom.xml
  console/src/main/java/org/georchestra/console/dao/AdminLogDao.java
  console/src/main/java/org/georchestra/console/ds/AccountDaoImpl.java
  console/src/main/java/org/georchestra/console/ds/RoleDaoImpl.java
  console/src/main/java/org/georchestra/console/dto/orgs/Org.java
  console/src/main/java/org/georchestra/console/dto/orgs/OrgExt.java
  console/src/main/java/org/georchestra/console/model/AdminLogEntry.java
  console/src/main/java/org/georchestra/console/model/AdminLogType.java
  console/src/main/java/org/georchestra/console/ws/backoffice/orgs/OrgsController.java
  console/src/main/java/org/georchestra/console/ws/backoffice/roles/RolesController.java
  console/src/main/java/org/georchestra/console/ws/backoffice/users/UsersController.java
  console/src/main/java/org/georchestra/console/ws/changepassword/ChangePasswordFormController.java
  console/src/main/java/org/georchestra/console/ws/editorgdetails/EditOrgDetailsFormController.java
  console/src/main/java/org/georchestra/console/ws/edituserdetails/EditUserDetailsFormController.java
  console/src/main/java/org/georchestra/console/ws/emails/EmailController.java
  console/src/main/java/org/georchestra/console/ws/newaccount/NewAccountFormController.java
  console/src/main/java/org/georchestra/console/ws/passwordrecovery/PasswordRecoveryFormController.java
  console/src/main/java/org/georchestra/console/ws/utils/LogUtils.java
  console/src/main/webapp/WEB-INF/spring/webmvc-config.xml
  console/src/main/webapp/manager/app/app.es6
  console/src/main/webapp/manager/app/assets/lang/de.json
  console/src/main/webapp/manager/app/assets/lang/en.json
  console/src/main/webapp/manager/app/assets/lang/es.json
  console/src/main/webapp/manager/app/assets/lang/fr.json
  console/src/main/webapp/manager/app/components/home/home.es6
  console/src/main/webapp/manager/app/components/home/home.tpl.html
  console/src/main/webapp/manager/app/components/logger/logger.es6
  console/src/main/webapp/manager/app/components/logger/logger.tpl.html
  console/src/main/webapp/manager/app/components/logs/logs.es6
  console/src/main/webapp/manager/app/components/logs/logs.tpl.html
  console/src/main/webapp/manager/app/components/user/user.es6
  console/src/main/webapp/manager/app/components/user/user.tpl.html
  console/src/test/java/org/georchestra/console/ds/AccountDaoTest.java
  console/src/test/java/org/georchestra/console/ws/backoffice/orgs/OrgsControllerTest.java
  console/src/test/java/org/georchestra/console/ws/backoffice/roles/RolesControllerTest.java
  console/src/test/java/org/georchestra/console/ws/backoffice/users/UsersControllerTest.java
  console/src/test/java/org/georchestra/console/ws/changepassword/ChangePasswordControllerTest.java
  console/src/test/java/org/georchestra/console/ws/editorgdetails/EditOrgDetailsFormControllerTest.java
  console/src/test/java/org/georchestra/console/ws/edituserdetails/EditUserDetailsFormControllerTest.java
  console/src/test/java/org/georchestra/console/ws/newaccount/NewAccountFormControllerTest.java
  console/src/test/java/org/georchestra/console/ws/passwordrecovery/PasswordRecoveryFormControllerTest.java
  console/src/test/java/org/georchestra/console/ws/utils/LogUtilsTest.java
  console/src/test/resources/webmvc-config-test.xml
Labels: feature

#2897 [console] validate role shortname
  console/src/main/webapp/manager/app/app.es6
  console/src/main/webapp/manager/app/assets/lang/de.json
  console/src/main/webapp/manager/app/assets/lang/en.json
  console/src/main/webapp/manager/app/assets/lang/es.json
  console/src/main/webapp/manager/app/assets/lang/fr.json
  console/src/main/webapp/manager/app/assets/lang/nl.json
  console/src/main/webapp/manager/app/components/org/org.es6
  console/src/main/webapp/manager/app/templates/roleForm.tpl.html
Labels: enhancement

#2832 analytics - rename groups into orgs / roles (depending on context)
  Makefile
  analytics/src/main/java/org/georchestra/analytics/OGCStats.java
  analytics/src/main/java/org/georchestra/analytics/StatisticsController.java
  analytics/src/main/java/org/georchestra/analytics/model/OGCStatsModel.java
  analytics/src/main/webapp/js/app/Application.js
  analytics/src/main/webapp/js/app/controller/OGC.js
  analytics/src/main/webapp/js/app/model/OGCOrg.js
  analytics/src/main/webapp/js/app/store/OGCOrgs.js
  analytics/src/main/webapp/js/app/view/OGCOrgs.js
  analytics/src/main/webapp/js/app/view/Viewport.js
  analytics/src/test/java/org/georchestra/analytics/StatisticsControllerTest.java
  analytics/test.sh
  cas-server-webapp/src/main/java/org/georchestra/cas/ldap/GeorchestraLdapAuthenticationHandler.java
  cas-server-webapp/src/main/java/org/georchestra/cas/ldap/WaitForLdap.java
Labels: bikeshedding
